/**
 * Planet-type vocabulary for validating and recovering OCR'd type lines.
 *
 * Generated from the NMSCD wiki page creator's datalists
 * (github.com/NMSCD/NMSWikiPageCreator, src/datalists/planetDatalists.ts),
 * which track the game's procedural descriptor tables, unioned with the
 * previously hand-curated words seen on real scans. Do not edit by hand —
 * regenerate from that file instead.
 */

/** Adjectives the game suffixes with "Planet"/"Moon" ("Verdant Planet"). */
export const BIOME_ADJECTIVES: string[] = [
  'Abandoned',
  'Acidic',
  'Acrid',
  'Airless',
  'Anomalous',
  'Aquatic',
  'Arctic',
  'Arid',
  'Ash-Shrouded',
  'Ashen',
  'Azure',
  'Barren',
  'Basalt',
  'Beam-Split',
  'Bizarre',
  'Bladed',
  'Bleak',
  'Blighted',
  'Blood',
  'Boggy',
  'Boiling',
  'Bone-Spire',
  'Bountiful',
  'Breached',
  'Bubbling',
  'Cabled',
  'Calcified',
  'Capped',
  'Caustic',
  'Cerulean',
  'Charred',
  'Chromatic Fog',
  'Cloudy',
  'Columned',
  'Contaminated',
  'Contoured',
  'Corrosive',
  'Corrupted',
  'Crimson',
  'Damp',
  'Dead',
  'Decaying',
  'Decaying Nuclear',
  'Desert',
  'Desolate',
  'Doomed',
  'Doomed Jade',
  'Drowning',
  'Dusty',
  'Empty',
  'Erased',
  'Erupting',
  'Exotic',
  'Fiery',
  'Finned',
  'Fissured',
  'Flame-Ruptured',
  'Flourishing',
  'Foaming',
  'Foggy',
  'Forsaken',
  'Fractured',
  'Fragmented',
  'Freezing',
  'Frostbound',
  'Frothing',
  'Frozen',
  'Fungal',
  'Gamma-Intensive',
  'Glacial',
  'Glassy',
  'Glitch',
  'Grassy',
  'Haunted Emeril',
  'Hazy',
  'Hexagonal',
  'Hiemal',
  'High Energy',
  'High Radio Source',
  'High Temperature',
  'Hot',
  'Humid',
  'Hyperborean',
  'Icebound',
  'Icy',
  'Incandescent',
  'Infected',
  'Infested',
  'Irradiated',
  'Isotopic',
  'Lava',
  'Life-Incompatible',
  'Lifeless',
  'Lost Blue',
  'Lost Green',
  'Lost Red',
  'Low Atmosphere',
  'Lush',
  'Magma',
  'Malfunctioning',
  'Marine',
  'Marshy',
  'Mechanical',
  'Mega Exotic',
  'Metallic',
  'Metallurgic',
  'Miasmatic',
  'Misty',
  'Molten',
  'Murky',
  'Mutated',
  'Noxious',
  'Nuclear',
  'Oceanic',
  'Ossified',
  'Overcast',
  'Overgrown',
  'Paradise',
  'Parched',
  'Petrified',
  'Pillared',
  'Plated',
  'Poisonous',
  'Quagmire',
  'Radioactive',
  'Rainy',
  'Rattling',
  'Reeking',
  'Rocky',
  'Rotting',
  'Scalding',
  'Scaly',
  'Scarlet',
  'Scorched',
  'Sharded',
  'Shattered',
  'Shell-Strewn',
  'Skeletal',
  'Spined',
  'Sporal',
  'Stony',
  'Sub-zero',
  'Supercritical',
  'Swamp',
  'Tainted',
  'Tectonic',
  'Temperate',
  'Temporary',
  'Thirsty',
  'Tidal',
  'Torrid',
  'Toxic',
  'Tropical',
  'Ultramarine',
  'Unstable',
  'Vapour',
  'Verdant',
  'Violent',
  'Viridescent',
  'Volcanic',
  'Waterlocked',
  'Webbed',
  'Weird',
  'Wind-swept',
  'Wine Dark',
  'Wire-Cell',
  'Worm-ridden',
  '[REDACTED]',
]

/** Complete type strings shown with no Planet/Moon noun ("Vermillion Globe"). */
export const STANDALONE_TYPES: string[] = [
  'Boiling Doom',
  'Caustic Nightmare',
  'Deathly Green Anomaly',
  'Endless Morass',
  'Endless Seas',
  'Fiery Dreadworld',
  'Frozen Anomaly',
  'Frozen Hell',
  'Harsh Blue Globe',
  'Icy Abhorrence',
  'Imminent Core Detonation',
  'Infected Dustbowl',
  'Infested Paradise',
  'Obsidian Bead',
  'Planetary Anomaly',
  'Radioactive Abomination',
  'Stellar Corruption Detected',
  'Terraforming Catastrophe',
  'Terrorsphere',
  'The Nest',
  'Toxic Anomaly',
  'Toxic Horror',
  'Vermillion Globe',
  'Vile Anomaly',
  'Waterworld',
  'Xeno-Colony',
]

/** Descriptors that follow the noun instead: "Planet of Light". */
export const TYPE_TAILS: string[] = [
  'of Light',
]
